### ISSUE TITLE
7.0 Roadmap

### ISSUE THREAD

**Issue by hasezoey** [typegoose/typegoose#113]
# 7.0 Roadmap

- [x] Set minimal needed node version to 10 [681c52dfb22b47664f9728aac6927e1e798251dd]
- [x] Upgrade to Typescript 3.8  #199 [dbdd276a446d9b937e4a568bb20ef3e7baa14a8d]
- [x] replace all `if-throw` checks with assert functions (requires node 10 or higher) #112 [f4b84135d72e3fb1bd335f479ba20d434d09dbb4]
- [x] fully remove the Typegoose Class [4733cf0dccf186e67e6b9f7e61f36921e7a21d43]
- [x] ~~refactor to use tsconfig "strict" #114~~ - removed due to being "impossible" because typegoose uses "dynamic lookup" (`this['something']`)
- [x] remove all deprecated `arrayProp` options
- [x] ~~Enable tslint rule "no-parameter-reassignment" #169~~ - removed because it would make the code messier and increase ram usage
- [x] Multidimensional Arrays #65  [8c980eaf69f4fedcf4d13a2ffc41df40c0931565]
- [x] Move some things to metadata instead of data.ts #44 [e57b995a3f628564353cf9dd2e6a13e981b16869]
- [x] Add null to enum #235 [1b0d224b90ce4c87fde5a0b00fcb32dd6ac80eaa]
- [x] custom query methods #148 [234963ffe462f36822467494b39c61434bc75362]
- [x] switch tests to jest instead of chai & mocha [21c26cd147f7d7c90789fdf8c444c871efc28dfc]

## Notes

Please know that 7.0 does not have an planned release date

**Comment by hasezoey** [comment]
final version from 6.x is now released (6.5)

**Comment by hasezoey** [comment]
`r7/master` is now merged into `master` (f234fa14b0c56d0eea433e4741b972c521261c92)

**Comment by hasezoey** [comment]
7.0.0 is now released
